### ISSUE TITLE
proposal: Refactor CSS

### ISSUE THREAD

**Issue by jmooring** [KKKZOZ/hugo-admonitions#5]
At the moment, overriding the color scheme is painful. The style sheet contains 58 hex color references and 23 rgba color references. I suggest refactoring this with a variables section at the top of the file. There should be one variable for each alert type, and everything else should be calculated against these values using Sass instead of CSS if necessary.

Justification: make it easier for site and theme authors to adapt this module to work with their site's color palette.

**Comment by KKKZOZ** [comment]
like this one?

```scss
$notice-colors: (
  info:       #04a5e5,
  notify:     #1e66f5,
  success:    #40a02b,
  warning:    #df8e1d,
  danger:     #fe640b,
  error:      #d20f39,
  task:       #8839ef,
  tip:        #179299,
  abstract:   #209fb5,
  conclusion: #dd7878,
  memo:       #e64553,
  question:   #179299,
  quote:      #7287fd,
  example:    #dc8a78,
  experiment: #dc8a78,
  goal:       #e64553,
  code:       #7287fd,
  idea:       #df8e1d,
  note:       #0966D8,
  important:  #7D4DDA,
  caution:    #e64553
);

$light-bg: #ffffff;
$dark-bg: #1D1E20;
$light-text: #000000;
$dark-text: #e6e6e6;
$light-code-bg: #f5f5f5;
$dark-code-bg: #313244;
$light-code-text: #24292e;
$dark-code-text: #cdd6f4;
$light-blockquote-border: #e0e0e0;
$dark-blockquote-border: #45475a;

.notice {
  margin: 1rem 0;
  border-radius: 4px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
  transition: all 0.3s ease;
}

.notice-header {
  padding: 0.5rem 1rem;
  display: flex;
  align-items: center;
  font-weight: 600;
  border-bottom: 1px solid rgba(0, 0, 0, 0.1);
  font-size: 1.1rem;
  border-radius: 4px 4px 0 0;
  
  svg {
    width: 1.1em;
    height: 1.1em;
    margin-right: 0.5rem;
    fill: currentColor;
  }
}

.notice-content {
  padding: 1rem;
  background-color: $light-bg;
  border-radius: 0 0 4px 4px;
  color: $light-text;
  transition: background-color 0.3s ease, color 0.3s ease;

  p {
    margin: 0 0 0.5rem 0;
    &:last-child { margin-bottom: 0; }
  }

  ul, ol {
    margin: 0 0 0.5rem 0;
    padding-left: 1.2rem;
    &:last-child { margin-bottom: 0; }
  }

  blockquote {
    margin: 0 0 0.5rem 0;
    padding-left: 1rem;
    border-left: 3px solid $light-blockquote-border;
    &:last-child { margin-bottom: 0; }
  }

  code {
    background-color: $light-code-bg;
    color: $light-code-text;
    padding: 0.2em 0.4em;
    border-radius: 3px;
    font-size: 0.9em;
  }
}

@media (prefers-color-scheme: dark) {
  .notice-content {
    background-color: $dark-bg;
    color: $dark-text;

    code {
      background-color: $dark-code-bg;
      color: $dark-code-text;
    }

    blockquote {
      border-left-color: $dark-blockquote-border;
      color: $dark-code-text;
    }
  }
}

body.dark {
  .notice-content {
    background-color: $dark-bg;
    color: $dark-text;

    code {
      background-color: $dark-code-bg;
      color: $dark-code-text;
    }

    blockquote {
      border-left-color: $dark-blockquote-border;
      color: $dark-code-text;
    }
  }
}

@each $type, $color in $notice-colors {
  .notice.#{$type} {
    background: transparent;
    border-left: 4px solid $color;
    
    .notice-header {
      background: rgba($color, 0.1);
      color: $color;
    }
  }
}
```
